// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQmC6HvglXnoXXaAVEvvPQnAsrBq7GGDY',
    appId: '1:923851836563:web:f7c8c95687f4f35a275166',
    messagingSenderId: '923851836563',
    projectId: 'project-ced1f',
    authDomain: 'project-ced1f.firebaseapp.com',
    storageBucket: 'project-ced1f.appspot.com',
    measurementId: 'G-TQWZ03Q6JM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAA7Z-YUqjKVGectZ9HzQdikPznLSclkOs',
    appId: '1:923851836563:android:ee36691f554fef9e275166',
    messagingSenderId: '923851836563',
    projectId: 'project-ced1f',
    storageBucket: 'project-ced1f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvSRzrG-3-Z1MSACiG_zhPN34Iqcco_So',
    appId: '1:923851836563:ios:db83496b3351a3be275166',
    messagingSenderId: '923851836563',
    projectId: 'project-ced1f',
    storageBucket: 'project-ced1f.appspot.com',
    iosBundleId: 'com.example.demo',
  );
}
